#!/bin/bash

set -e

VSCODE_SETTINGS_PATH="./.vscode/settings.json"
if [ -f "$VSCODE_SETTINGS_PATH" ]; then
    LOCAL_SETTINGS=$(jq -s 'add' $VSCODE_SETTINGS_PATH ./settings.json)
    echo $LOCAL_SETTINGS > $VSCODE_SETTINGS_PATH
else

# default to codespace user
if [ -z "${USER}" ]; then
  USER=codespace
fi

USER_HOME=$(getent passwd $USER | cut -d: -f6)

echo "Changing shell to zsh for ${USER}..."
# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "${USER}.*/bin/zsh" /etc/passwd
then
  sudo chsh -s /bin/zsh ${USER}
fi

# set up org specific overrides
if [[ "$CODESPACE_NAME" =~ .*"github".* ]]; then
  echo "Installing GitHub codespace related dotoverrides configs..."
  echo -e "[user]\n  email = itoys@github.com" >> gitconfig

  echo "machine goproxy.githubapp.com login nobody password ${GITHUB_TOKEN}" > ${USER_HOME}/.netrc
fi

# install linuxbrew suggested packages
sudo apt-get install build-essential
