#!/bin/bash

set -e

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "codespace.*/bin/zsh" /etc/passwd
then
  sudo chsh -s /bin/zsh codespace
fi

# set up org specific overrides
if [[ "$CODESPACE_NAME" =~ .*"github".* ]]; then
  mkdir -p dotoverrides
  echo "Installing GitHub codespace related dotoverrides configs..."
  echo -e "[user]\n  email = itoys@github.com" >> dotoverrides/gitconfig
fi

# install linuxbrew suggested packages
sudo apt-get install build-essential
